hearingRangeMeters: 50.0
garbleRangeDivisor: 2.0
yellMax: 4
yell.1.hunger: 1
yell.2.hunger: 2
yell.3.hunger: 4
yell.4.hunger: 20
yell.1.rangeIncrease: 10.0
yell.2.rangeIncrease: 50.0
yell.3.rangeIncrease: 100.0
yell.4.rangeIncrease: 500.0
whisperRangeDecrease: 10
megaphoneFactor: 2.0
walkieRange: 1000.0

