speakingRangeMeters: 50.0
garbleRangeDivisor: 2.0
garblePartialChance: 0.10
garbleAllDroppedMessage: "~~~"
chatLineFormat: "%1$s: %2$s"
chatSpokenPlayerColor: YELLOW
chatHeardPlayerColor: GREEN
chatMessageColor: WHITE
chatDimMessageColor: DARK_GRAY
yellMax: 4
yell.1.hunger: 1
yell.2.hunger: 2
yell.3.hunger: 4
yell.4.hunger: 20
yell.1.rangeIncrease: 10.0
yell.2.rangeIncrease: 50.0
yell.3.rangeIncrease: 100.0
yell.4.rangeIncrease: 500.0
whisperRangeDecrease: 40.0
bullhornEnable: true
bullhornItem: diamond
bullhornFactor: 2.0
bullhornWidthDegrees: 70.0
earTrumpetEnable: true
earTrumpetEnableCrafting: true
earTrumpet.1.rangeIncrease: 100.0
earTrumpet.2.rangeIncrease: 150.0
earTrumpet.3.rangeIncrease: 400.0
walkieEnable: true
walkieItem: compass
walkieRangeMeters: 2000.0
walkieGarbleDivisor: 2.0
globalPrefix: '/g '
smartphoneEnable: true
smartphoneItem: watch

