name: RealisticChat
main: me.exphc.RealisticChat.RealisticChat
version: 2.0
website: http://dev.bukkit.org/server-mods/realisticchat/
description: realistic local chat!
authors: [cakenggt, mushroomhostage]
